name: Run certificate expiry check

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 4 22 * * 1

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Execute the checks
        run: python check.py
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}

      - name: Commit and push files
        run: |
          git pull
          git config --local user.email "empty@example.org"
          git config --local user.name "Cert Checker Bot"
          git add README.md
          git diff --exit-code --cached || exit_code=$?
          echo $exit_code
          if (( exit_code > 0 )); then
            git commit -m "Update README with expiry dates" && \
            git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:main
          fi
